import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { FormModel } from '../models/form';

@Injectable({
  providedIn: 'root'
})
export class DataProviderService {

  private data: FormModel[] = [
    {
      id: 1,
      name: 'Severance Agreement',
      description: 'Open Adaptive Form',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/static.pdf',
      url2: 'assets/pdf/ui2.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p.png'
    },
    {
      id: 2,
      name: 'Onboard candidate',
      description: 'Open Adaptive Form 2',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p1.png'
    },
    {
      id: 3,
      name: 'Human resources',
      description: 'Open Adaptive Form 3',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p2.png'
    },
    {
      id: 4,
      name: 'Confidentiality Agreement',
      description: 'Open Adaptive Form 4',
      url: 'www',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p3.png'
    },
    {
      id: 5,
      name: 'Confidentiality',
      description: 'Open Adaptive Form 5',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 6,
      name: 'Agreement',
      description: 'Open Adaptive Form 6',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 7,
      name: 'Advertisement',
      description: 'Open Adaptive Form 7',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 8,
      name: 'Allowed',
      description: 'Open Adaptive Form 8',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 9,
      name: 'Amount',
      description: 'Open Adaptive Form 9',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 10,
      name: 'Bill',
      description: 'Open Adaptive Form 10',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 11,
      name: 'Branch',
      description: 'Open Adaptive Form 11',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 12,
      name: 'Brand',
      description: 'Open Adaptive Form 12',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },{
      id: 13,
      name: 'Brochure',
      description: 'Open Adaptive Form 13',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 14,
      name: 'Business',
      description: 'Open Adaptive Form 15',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 15,
      name: 'Colleague',
      description: 'Open Adaptive Form 15',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 16,
      name: 'Conference ',
      description: 'Open Adaptive Form 16',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 17,
      name: 'Currency',
      description: 'Open Adaptive Form 17',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 18,
      name: 'Employer',
      description: 'Open Adaptive Form 18',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 19,
      name: 'Entrepreneur',
      description: 'Open Adaptive Form 19',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 20,
      name: 'Invoice',
      description: 'Open Adaptive Form 20',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 21,
      name: 'Loan',
      description: 'Open Adaptive Form 21',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 22,
      name: 'Marketing',
      description: 'Open Adaptive Form 22',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 23,
      name: 'Package',
      description: 'Open Adaptive Form 23',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 24,
      name: 'Production Departmen',
      description: 'Open Adaptive Form 24',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
    {
      id: 25,
      name: 'Promotion',
      description: 'Open Adaptive Form 25',
      url: 'assets/pdf/ui.pdf',
      url1: 'assets/pdf/ui.pdf',
      url2: 'assets/pdf/ui.pdf',
      url3: 'assets/pdf/ui.pdf',
      img: 'assets/img/p4.png',
    },
  ];

  constructor(private http: HttpClient) {}

  getInfo(): Observable<FormModel[]>{
    return this.http.get<FormModel[]>('http://localhost:80/local.php');
  }

  getData(): FormModel[]{
    return this.data;
  }
}
